import { useEffect, useMemo, useState } from "react";
import { getVersion } from "@tauri-apps/api/app";
import {
  addFinding, addProject, addReport, addScan, addTarget, deleteProject, deleteReport, deleteTarget,
  initDatabase, listAudit, listFindings, listProjects, listReports, listScans, listTargets,
  updateFinding, updateProject, updateScan, updateTarget, type AuditRecord, type FindingRecord, type ProjectRecord,
  type ReportRecord, type ScanRecord, type TargetRecord
} from "./db";
import { runScan, type ScanModule } from "./scanner";
import { buildAssessmentReport, openAssessmentReport } from "./report";
import { checkForUpdate, restartAfterUpdate, type UpdateProgress } from "./update";
import { exportAssessmentData } from "./backup";

type Project=ProjectRecord&{id:number}; type Target=TargetRecord&{id:number}; type Scan=ScanRecord&{id:number}; type Finding=FindingRecord&{id:number};

const sections=["Dashboard","Projects","Targets","Scans","Findings","Reports","Settings"];
const modules:[ScanModule,string,string][]=[["assessment","Full assessment","Headers + TLS + technology"],["headers","Security headers","HTTP security configuration"],["tls","TLS","Certificate and protocol analysis"],["technology","Technology","Detected frameworks and libraries"]];

function allowedTarget(value:string){try{const u=new URL(value);return ["http:","https:"].includes(u.protocol)&&!u.username&&!u.password&&(!u.port||["80","443"].includes(u.port))&&!!u.hostname}catch{return false}}
function sevClass(s:string){return s.toLowerCase().replace(/[^a-z]/g,"")}
function fmt(v?:string){if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString()}
function daysUntilExpiry(expiryStr?:string){if(!expiryStr)return null;const d=new Date(expiryStr);const now=new Date();const days=Math.floor((d.getTime()-now.getTime())/(1000*60*60*24));return days>0?`${days}d`:`expired`}

export default function App(){
  const [active,setActive]=useState("Dashboard"),[version,setVersion]=useState("0.1.0"),[loaded,setLoaded]=useState(false),[error,setError]=useState("");
  const [projects,setProjects]=useState<Project[]>([]),[targets,setTargets]=useState<Target[]>([]),[scans,setScans]=useState<Scan[]>([]),[findings,setFindings]=useState<Finding[]>([]);
  const [reports,setReports]=useState<ReportRecord[]>([]),[audit,setAudit]=useState<AuditRecord[]>([]);
  const [selectedProject,setSelectedProject]=useState<number|"">(""),[targetUrl,setTargetUrl]=useState(""),[targetName,setTargetName]=useState(""),[targetEnv,setTargetEnv]=useState("production"),
      [targetTags,setTargetTags]=useState(""),[scopeConfirmed,setScopeConfirmed]=useState(false),[targetAuthExpiry,setTargetAuthExpiry]=useState("");
  const [projectName,setProjectName]=useState(""),[client,setClient]=useState(""),[projectDescription,setProjectDescription]=useState("");
  const [scanModule,setScanModule]=useState<ScanModule>("assessment"),[running,setRunning]=useState<number[]>([]),[reportScanId,setReportScanId]=useState<number|"">("");
  const [findingFilter,setFindingFilter]=useState("all"),[checkingUpdate,setCheckingUpdate]=useState(false),[updateText,setUpdateText]=useState("");
  const [editProject,setEditProject]=useState<Project|null>(null),[editTarget,setEditTarget]=useState<Target|null>(null),[selectedFinding,setSelectedFinding]=useState<Finding|null>(null);

  async function reload(){const [p,t,s,r,a,f]=await Promise.all([listProjects(),listTargets(),listScans(),listReports(),listAudit(),listFindings()]);setProjects(p as Project[]);setTargets(t as Target[]);setScans(s as Scan[]);setFindings(f as Finding[]);setReports(r);setAudit(a)}
  useEffect(()=>{Promise.all([initDatabase(),getVersion()]).then(async([,v])=>{setVersion(v);await reload();setLoaded(true)}).catch(e=>setError(e instanceof Error?e.message:String(e)))},[]);

  async function createProject(){setError("");if(!projectName.trim())return setError("Project name is required.");try{await addProject({name:projectName.trim(),client:client.trim(),description:projectDescription.trim(),status:"active",createdAt:new Date().toISOString()});setProjectName("");setClient("");setProjectDescription("");await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function saveProjectEdit(){if(!editProject)return;setError("");if(!editProject.name.trim())return setError("Project name is required.");try{await updateProject(editProject.id,{name:editProject.name,client:editProject.client,description:editProject.description,status:editProject.status});setEditProject(null);await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function removeProject(){if(!editProject)return;setError("");try{await deleteProject(editProject.id);setEditProject(null);await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}

  async function createTarget(){setError("");if(!selectedProject)return setError("Select a project first.");if(!scopeConfirmed)return setError("Confirm that you own this target or have explicit authorization.");if(!allowedTarget(targetUrl))return setError("Target must be a valid HTTP(S) URL.");try{await addTarget({projectId:Number(selectedProject),url:targetUrl.trim(),name:targetName.trim()||undefined,environment:targetEnv,tags:targetTags.trim()||undefined,authorized:scopeConfirmed,authorizationExpiresAt:targetAuthExpiry?new Date(targetAuthExpiry).toISOString():undefined,createdAt:new Date().toISOString()});setTargetUrl("");setTargetName("");setTargetEnv("production");setTargetTags("");setScopeConfirmed(false);await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function saveTargetEdit(){if(!editTarget)return;setError("");if(!allowedTarget(editTarget.url))return setError("Target must be a valid HTTP(S) URL.");try{const expiry=editTarget.authorizationExpiresAt?new Date(editTarget.authorizationExpiresAt).toISOString():"";await updateTarget(editTarget.id,{url:editTarget.url,name:editTarget.name,environment:editTarget.environment,tags:editTarget.tags,authorized:editTarget.authorized,authorizationExpiresAt:expiry||undefined});setEditTarget(null);await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function removeTarget(){if(!editTarget)return;setError("");try{await deleteTarget(editTarget.id);setEditTarget(null);await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}

  async function startScan(t:Target,module=scanModule){setError("");if(!t.authorized)return setError("This target is not authorized.");if(t.authorizationExpiresAt&&new Date(t.authorizationExpiresAt)<new Date())return setError("Authorization for this target has expired.");setRunning([...running,t.id]);try{const result=await runScan(t.url,module);const scan:ScanRecord={targetId:t.id,projectId:t.projectId,scanner:module,status:"completed",findingsCount:result.findings.length,statusCode:result.status_code,finalUrl:result.url,createdAt:new Date().toISOString()};const addedScan=await addScan(scan);for(const f of result.findings){await addFinding({scanId:addedScan.id||0,targetId:t.id,check:f.check,title:f.title,severity:f.severity,status:"open",description:f.description,evidence:f.evidence,recommendation:f.recommendation,reference:f.reference,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})}await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setRunning(current=>current.filter(id=>id!==t.id))}}

  async function updateFindingStatus(f:Finding,newStatus:string){setError("");try{await updateFinding(f.id!,{status:newStatus,updatedAt:new Date().toISOString()});setSelectedFinding(null);await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}

  async function generateReport(scan:Scan){const t=targets.find(x=>x.id===scan.targetId);if(!t)return setError("Target no longer exists.");const fs=findings.filter(x=>x.scanId===scan.id);const proj=projects.find(x=>x.id===scan.projectId);if(!proj)return setError("Project no longer exists.");try{const html=await buildAssessmentReport({project:proj,target:t,scan,findings:fs});const report:ReportRecord={projectId:proj.id,scanId:scan.id,name:`${t.url} - ${fmt(scan.createdAt)}`,createdAt:new Date().toISOString()};await addReport(report);await openAssessmentReport(html);setReportScanId("");await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}

  async function deleteReportRecord(r:ReportRecord){setError("");try{await deleteReport(r.id!);await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}

  async function checkUpdates(){setCheckingUpdate(true);setUpdateText("Checking GitHub release channel…");try{const result=await checkForUpdate((p:UpdateProgress)=>{if(p.event==="Started")setUpdateText(`Downloading update (${p.contentLength?Math.round(p.contentLength/1024/1024)+"mb":"?"})…`);else if(p.event==="Progress")setUpdateText(`Downloaded ${Math.round(p.downloaded/1024/1024)}mb of ${p.contentLength?Math.round(p.contentLength/1024/1024):"?"}mb…`);else if(p.event==="Finished")setUpdateText("Update complete. Restarting…")});if(result){setUpdateText(`Ready to install v${result.version}. Restarting…`);await restartAfterUpdate()}else{setUpdateText("");setCheckingUpdate(false)}}catch(e){setUpdateText("");setCheckingUpdate(false);setError(e instanceof Error?e.message:String(e))}}

  const openFindings=findings.filter(f=>f.status!=="resolved"&&f.status!=="false positive"),critical=findings.filter(f=>f.severity.toLowerCase()==="critical").length,high=findings.filter(f=>f.severity.toLowerCase()==="high").length,medium=findings.filter(f=>f.severity.toLowerCase()==="medium").length;
  const projectTargets=selectedProject?targets.filter(t=>t.projectId===Number(selectedProject)):[];
  const filteredFindings=findingFilter==="all"?findings:findings.filter(f=>f.severity.toLowerCase()===findingFilter);
  if(!loaded)return <div className="loading-screen"><div className="loading-mark">DD</div><b>Starting DadaDevourer</b><span>Loading local assessment database…</span></div>;

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark">DD</div><div><strong>DadaDevourer</strong><span>Security assessment</span></div></div>
      <div className="side-label">WORKSPACE</div><nav>{sections.map(s=><button key={s} className={active===s?"nav-item active":"nav-item"} onClick={()=>{setError("");setActive(s)}}><span className="nav-glyph">{s[0]}</span>{s}</button>)}</nav>
      <div className="scope-card"><span className="status-dot"/><div><b>Local engine ready</b><small>Authorized testing only</small></div></div>
    </aside>
    <main className="content">
      <header className="topbar"><div><span className="eyebrow">DADADEVOURER • DESKTOP</span><h1>{active}</h1></div><div className="top-actions"><span className="engine-state"><span className="status-dot"/>{version}</span><button onClick={checkUpdates} disabled={checkingUpdate}>{checkingUpdate?"Checking...":"Check update"}</button></div></header>
      {error&&<div className="error-banner"><b>Action needs attention</b><span>{error}</span><button onClick={()=>setError("")}>×</button></div>}
      {updateText&&<div className="info-banner">{updateText}</div>}

      {active==="Dashboard"&&<><section className="hero"><div><span className="eyebrow">WELCOME TO DADADEVOURER</span><h2>Start your first authorized security assessment.</h2><p>Create a project, add a target you own or are explicitly authorized to test, then run a controlled assessment.</p><div className="hero-actions"><button onClick={()=>setActive("Projects")}>Create first project</button><button className="secondary" onClick={()=>setActive("Targets")}>Add authorized target</button></div></div></section>\n      {projects.length===0&&<section className="panel onboarding-panel"><div className="panel-heading"><div><h3>First launch checklist</h3><p>No projects exist yet. Your local database is ready.</p></div></div><div className="workflow-list"><div>1. Create an assessment project</div><div>2. Add only an authorized HTTP/HTTPS target</div><div>3. Confirm the testing scope</div><div>4. Run a controlled scan and review findings</div></div></section>}
      <section className="stats"><div><span>Projects</span><b>{projects.length}</b><small>Assessment workspaces</small></div><div><span>Authorized targets</span><b>{targets.filter(t=>t.authorized).length}</b><small>Scanned systems</small></div><div><span>Completed scans</span><b>{scans.length}</b><small>Assessment runs</small></div><div><span>Findings</span><b>{openFindings.length}</b><small>Open issues</small></div></section>
      <section className="grid-2"><div className="panel"><div className="panel-heading"><div><h3>Assessment workflow</h3><p>Keep every test tied to an authorized project.</p></div></div><div className="workflow-list"><div>1. Create project</div><div>2. Add target with authorization</div><div>3. Run security scan</div><div>4. Review findings</div><div>5. Generate report</div></div></div>
      <div className="panel"><div className="panel-heading"><div><h3>Risk overview</h3><p>Current findings from all local scans.</p></div></div><div className="risk-list">{[["Critical",critical],["High",high],["Medium",medium]].map(([l,c])=><div key={l}><span>{l}</span><b>{c}</b></div>)}</div></div></section></>}

      {active==="Projects"&&<section className="grid-2"><div className="panel"><div className="panel-heading"><div><h3>New assessment project</h3><p>Every target and scan belongs to a project.</p></div></div><div className="form-grid"><label><span>Project name</span><input type="text" value={projectName} onChange={e=>setProjectName(e.target.value)} placeholder="e.g., Acme Corp Q4 Assessment"/></label><label><span>Client</span><input type="text" value={client} onChange={e=>setClient(e.target.value)} placeholder="e.g., Acme Corporation"/></label><label className="full"><span>Description</span><input type="text" value={projectDescription} onChange={e=>setProjectDescription(e.target.value)} placeholder="Assessment scope and objectives"/></label></div><button onClick={createProject}>Create project</button></div>
      <div className="panel"><div className="panel-heading"><div><h3>Assessment projects</h3><p>{projects.length===0?"No projects created yet.":""}</p></div></div>{projects.length===0?<Empty title="No projects" text="Create a new assessment project to begin."/>:<div className="list">{projects.map(p=><div key={p.id} className="list-row"><div><b>{p.name}</b><small>{p.client}</small></div><div className="list-actions"><button className="icon-button" onClick={()=>setEditProject(p)}>✎</button></div></div>)}</div>}</div></section>}

      {active==="Targets"&&<section className="grid-2"><div className="panel"><div className="panel-heading"><div><h3>Add authorized target</h3><p>A scope confirmation is required for every target.</p></div></div><div className="form-grid"><label className="full"><span>Project</span><select value={selectedProject} onChange={e=>setSelectedProject(e.target.value)}><option value="">Select project...</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="full"><span>Target URL</span><input type="url" value={targetUrl} onChange={e=>setTargetUrl(e.target.value)} placeholder="https://example.com"/></label><label><span>Name (optional)</span><input type="text" value={targetName} onChange={e=>setTargetName(e.target.value)} placeholder="e.g., API server"/></label><label><span>Environment</span><select value={targetEnv} onChange={e=>setTargetEnv(e.target.value)}><option>production</option><option>staging</option><option>development</option></select></label><label className="full"><span>Tags (optional)</span><input type="text" value={targetTags} onChange={e=>setTargetTags(e.target.value)} placeholder="web,api,critical"/></label><label className="full"><span>Authorization expires (optional)</span><input type="date" value={targetAuthExpiry} onChange={e=>setTargetAuthExpiry(e.target.value)}/></label><label className="full"><input type="checkbox" checked={scopeConfirmed} onChange={e=>setScopeConfirmed(e.target.checked)}/><span>I own this target or have explicit authorization to test it</span></label></div><button onClick={createTarget}>Add target</button></div>
      <div className="panel"><div className="panel-heading"><div><h3>Authorized targets</h3><p>{targets.length===0?"No targets added yet.":""}</p></div></div>{targets.length===0?<Empty title="No targets" text="Add an authorized target to begin scanning."/>:<div className="list">{targets.map(t=><div key={t.id} className="list-row"><div><b>{t.name||t.url}</b><small>{t.environment}{t.authorized?" • Authorized":""}{t.authorizationExpiresAt?` • Expires ${fmt(t.authorizationExpiresAt)}`:""}</small></div><div className="list-actions"><button className="icon-button" onClick={()=>setEditTarget(t)}>✎</button></div></div>)}</div>}</div></section>}

      {active==="Scans"&&<section className="panel"><div className="panel-heading"><div><h3>Assessment runs</h3><p>Run one controlled module or the complete local assessment.</p></div><div className="scan-launch"><select value={scanModule} onChange={e=>setScanModule(e.target.value as ScanModule)}>{modules.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div><div className="scan-table"><div className="table-head"><b>Target</b><b>Module</b><b>Status</b><b>Findings</b><b></b></div>{scans.map(scan=>{const t=targets.find(x=>x.id===scan.targetId);return <div key={scan.id} className="table-row"><div>{t?.name||t?.url}</div><div>{scan.scanner}</div><div>{scan.status}</div><div>{scan.findingsCount}</div><div>{!running.includes(scan.targetId||0)?<button onClick={()=>startScan(t!,scan.scanner as ScanModule)}>Scan</button>:<span>Running...</span>}</div></div>})}</div></section>}

      {active==="Findings"&&<section className="panel"><div className="panel-heading"><div><h3>Findings & evidence</h3><p>Review, classify and track observations from completed scans.</p></div><div><select value={findingFilter} onChange={e=>setFindingFilter(e.target.value)}><option value="all">All findings</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option></select></div></div><div className="list">{filteredFindings.length===0?<Empty title="No findings" text="Run a scan to identify potential issues."/>:filteredFindings.map(f=><div key={f.id} className="list-row"><div><b>{f.title||f.check}</b><small className={`severity-${sevClass(f.severity)}`}>{f.severity}</small><small>{f.status}</small></div><div className="list-actions"><button className="icon-button" onClick={()=>setSelectedFinding(f)}>→</button></div></div>)}</div></section>}

      {active==="Reports"&&<section className="grid-2"><div className="panel"><div className="panel-heading"><div><h3>Generate assessment report</h3><p>Build a local report from a completed scan.</p></div></div><div className="form-grid"><label className="full"><span>Select scan</span><select value={reportScanId} onChange={e=>setReportScanId(e.target.value?Number(e.target.value):"")}><option value="">Choose a scan...</option>{scans.map(s=>{const t=targets.find(x=>x.id===s.targetId);return <option key={s.id} value={s.id}>{t?.name||t?.url} - {fmt(s.createdAt)}</option>})}</select></label></div><button onClick={()=>reportScanId&&generateReport(scans.find(s=>s.id===reportScanId)!)} disabled={!reportScanId}>Generate report</button></div>
      <div className="panel"><div className="panel-heading"><div><h3>Report history</h3><p>{reports.length===0?"No reports generated yet.":""}</p></div></div>{reports.length===0?<Empty title="No reports" text="Generate a report from a completed scan."/>:<div className="list">{reports.map(r=><div key={r.id} className="list-row"><div><b>{r.name}</b><small>{fmt(r.createdAt)}</small></div><div className="list-actions"><button className="icon-button" onClick={()=>deleteReportRecord(r)}>✕</button></div></div>)}</div>}</div></section>}

      {active==="Settings"&&<section className="grid-2"><div className="panel"><div className="panel-heading"><div><h3>Application</h3><p>Local-first security assessment workstation.</p></div></div><div className="settings-row"><div><b>Version</b><small>{version}</small></div><button onClick={checkUpdates} disabled={checkingUpdate}>{checkingUpdate?"Checking...":"Check for updates"}</button></div><div className="settings-actions"><button onClick={async()=>await exportAssessmentData({projects,targets,scans:scans,findings,reports,audit})}>Export all data</button><small>Backup all assessment data as JSON</small></div></div>
      <div className="panel"><div className="panel-heading"><div><h3>Data export</h3><p>Export all assessment data as JSON for backup.</p></div></div><button onClick={async()=>{try{await exportAssessmentData({projects,targets,scans,findings,reports,audit})}catch(e){setError(e instanceof Error?e.message:String(e))}}}>Export assessment</button><small>Downloads JSON file with all projects, targets, scans, findings, and reports</small></div></section>}

      {editProject&&<div className="modal-overlay" onClick={()=>setEditProject(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>Edit project</h2><button className="close-button" onClick={()=>setEditProject(null)}>×</button></div><div className="modal-body"><div className="form-grid"><label><span>Project name</span><input type="text" value={editProject.name} onChange={e=>setEditProject({...editProject,name:e.target.value})}/></label><label><span>Client</span><input type="text" value={editProject.client} onChange={e=>setEditProject({...editProject,client:e.target.value})}/></label><label className="full"><span>Description</span><input type="text" value={editProject.description||""} onChange={e=>setEditProject({...editProject,description:e.target.value})}/></label></div></div><div className="modal-actions"><button onClick={saveProjectEdit}>Save</button><button className="secondary" onClick={removeProject}>Delete</button></div></div></div>}

      {editTarget&&<div className="modal-overlay" onClick={()=>setEditTarget(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>Edit target</h2><button className="close-button" onClick={()=>setEditTarget(null)}>×</button></div><div className="modal-body"><div className="form-grid"><label className="full"><span>URL</span><input type="url" value={editTarget.url} onChange={e=>setEditTarget({...editTarget,url:e.target.value})}/></label><label><span>Name</span><input type="text" value={editTarget.name||""} onChange={e=>setEditTarget({...editTarget,name:e.target.value})}/></label><label><span>Environment</span><select value={editTarget.environment||"production"} onChange={e=>setEditTarget({...editTarget,environment:e.target.value})}><option>production</option><option>staging</option><option>development</option></select></label><label className="full"><span>Authorization expires</span><input type="date" value={editTarget.authorizationExpiresAt?editTarget.authorizationExpiresAt.split("T")[0]:""} onChange={e=>setEditTarget({...editTarget,authorizationExpiresAt:e.target.value?new Date(e.target.value).toISOString():undefined})}/></label><label><input type="checkbox" checked={editTarget.authorized} onChange={e=>setEditTarget({...editTarget,authorized:e.target.checked})}/><span>Authorized</span></label></div></div><div className="modal-actions"><button onClick={saveTargetEdit}>Save</button><button className="secondary" onClick={removeTarget}>Delete</button></div></div></div>}

      {selectedFinding&&<div className="modal-overlay" onClick={()=>setSelectedFinding(null)}><div className="modal modal-lg" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>{selectedFinding.title||selectedFinding.check}</h2><button className="close-button" onClick={()=>setSelectedFinding(null)}>×</button></div><div className="modal-body"><div><b>Severity:</b> <span className={`severity-${sevClass(selectedFinding.severity)}`}>{selectedFinding.severity}</span></div><div><b>Status:</b> {selectedFinding.status}</div>{selectedFinding.description&&<div><b>Description:</b><p>{selectedFinding.description}</p></div>}{selectedFinding.evidence&&<div><b>Evidence:</b><p>{selectedFinding.evidence}</p></div>}{selectedFinding.recommendation&&<div><b>Recommendation:</b><p>{selectedFinding.recommendation}</p></div>}{selectedFinding.reference&&<div><b>Reference:</b><p>{selectedFinding.reference}</p></div>}</div><div className="modal-actions"><select value={selectedFinding.status} onChange={e=>updateFindingStatus(selectedFinding,e.target.value)}><option value="open">Open</option><option value="confirmed">Confirmed</option><option value="false positive">False Positive</option><option value="accepted">Accepted Risk</option><option value="resolved">Resolved</option></select></div></div></div>}

      {reportScanId&&<div className="modal-overlay" onClick={()=>setReportScanId("")}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>Generate Report</h2><button className="close-button" onClick={()=>setReportScanId("")}>×</button></div><div className="modal-body"><p>Generating report for scan...</p></div></div></div>}
    </main>
  </div>
}

function Empty({title,text}:{title:string;text:string}){return <div className="empty-state"><div className="empty-icon">—</div><h2>{title}</h2><p>{text}</p></div>}
