import { useEffect, useMemo, useState } from "react";
import { getVersion } from "@tauri-apps/api/app";
import {
  addFinding, addProject, addReport, addScan, addTarget, deleteProject, deleteReport, deleteTarget,
  initDatabase, listAudit, listFindings, listProjects, listReports, listScans, listTargets,
  updateFinding, updateProject, updateScan, updateTarget, type AuditRecord, type FindingRecord, type ProjectRecord,
  type ReportRecord, type ScanRecord, type TargetRecord
} from "./db";
import { runScan, type ScanModule } from "./scanner";
import { buildAssessmentReport, openAssessmentReport } from "./report";
import { checkForUpdate, restartAfterUpdate, type UpdateProgress } from "./update";

type Project=ProjectRecord&{id:number}; type Target=TargetRecord&{id:number}; type Scan=ScanRecord&{id:number}; type Finding=FindingRecord&{id:number};

const sections=["Dashboard","Projects","Targets","Scans","Findings","Reports","Settings"];
const modules:[ScanModule,string,string][]=[["assessment","Full assessment","Headers + TLS + technology"],["headers","Security headers","HTTP security configuration"],["tls","TLS","Certificate and protocol"],["technology","Technology","Server and framework disclosure"]];

function allowedTarget(value:string){try{const u=new URL(value);return ["http:","https:"].includes(u.protocol)&&!u.username&&!u.password&&(!u.port||["80","443"].includes(u.port))&&!!u.hostname}catch{return false}}
function sevClass(s:string){return s.toLowerCase().replace(/[^a-z]/g,"")}
function fmt(v?:string){if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString()}
function daysUntilExpiry(expiryStr?:string){if(!expiryStr)return null;const d=new Date(expiryStr);const now=new Date();const days=Math.floor((d.getTime()-now.getTime())/(1000*60*60*24));return days>=0?days:null}

export default function App(){
  const [active,setActive]=useState("Dashboard"),[version,setVersion]=useState("0.1.0"),[loaded,setLoaded]=useState(false),[error,setError]=useState("");
  const [projects,setProjects]=useState<Project[]>([]),[targets,setTargets]=useState<Target[]>([]),[scans,setScans]=useState<Scan[]>([]),[findings,setFindings]=useState<Finding[]>([]);
  const [reports,setReports]=useState<ReportRecord[]>([]),[audit,setAudit]=useState<AuditRecord[]>([]);
  const [selectedProject,setSelectedProject]=useState<number|"">(""),[targetUrl,setTargetUrl]=useState(""),[targetName,setTargetName]=useState(""),[targetEnv,setTargetEnv]=useState("production"),
      [targetTags,setTargetTags]=useState(""),[scopeConfirmed,setScopeConfirmed]=useState(false),[targetAuthExpiry,setTargetAuthExpiry]=useState("");
  const [projectName,setProjectName]=useState(""),[client,setClient]=useState(""),[projectDescription,setProjectDescription]=useState("");
  const [scanModule,setScanModule]=useState<ScanModule>("assessment"),[running,setRunning]=useState<number[]>([]),[reportScanId,setReportScanId]=useState<number|"">("");
  const [findingFilter,setFindingFilter]=useState("all"),[checkingUpdate,setCheckingUpdate]=useState(false),[updateText,setUpdateText]=useState("");
  const [editProject,setEditProject]=useState<Project|null>(null),[editTarget,setEditTarget]=useState<Target|null>(null),[selectedFinding,setSelectedFinding]=useState<Finding|null>(null);

  async function reload(){const [p,t,s,r,a]=await Promise.all([listProjects(),listTargets(),listScans(),listReports(),listAudit()]);setProjects(p as Project[]);setTargets(t as Target[]);setScans(s as Scan[]);setFindings((await listFindings()) as Finding[]);setReports(r);setAudit(a)}
  useEffect(()=>{Promise.all([initDatabase(),getVersion()]).then(async([,v])=>{setVersion(v);await reload();setLoaded(true)}).catch(e=>setError(e instanceof Error?e.message:String(e)))},[]);

  async function createProject(){setError("");if(!projectName.trim())return setError("Project name is required.");try{await addProject({name:projectName.trim(),client:client.trim(),description:projectDescription.trim(),status:"active",createdAt:new Date().toISOString()});setProjectName("");setClient("");setProjectDescription("");await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function saveProjectEdit(){if(!editProject)return;setError("");if(!editProject.name.trim())return setError("Project name is required.");try{await updateProject(editProject.id,{name:editProject.name,client:editProject.client,description:editProject.description,status:editProject.status});setEditProject(null);await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function removeProject(){if(!editProject)return;setError("");try{await deleteProject(editProject.id);setEditProject(null);await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}

  async function createTarget(){setError("");if(!selectedProject)return setError("Select a project first.");if(!scopeConfirmed)return setError("Confirm that you own this target or have explicit authorization.");if(!allowedTarget(targetUrl))return setError("Target must be a valid HTTP(S) URL without credentials (port 80 or 443 only).");try{const expiry=targetAuthExpiry?new Date(targetAuthExpiry).toISOString():undefined;await addTarget({projectId:Number(selectedProject),url:targetUrl.trim(),name:targetName.trim()||undefined,environment:targetEnv,tags:targetTags||undefined,authorized:scopeConfirmed,authorizationExpiresAt:expiry,createdAt:new Date().toISOString()});setTargetUrl("");setTargetName("");setTargetEnv("production");setTargetTags("");setScopeConfirmed(false);setTargetAuthExpiry("");await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function saveTargetEdit(){if(!editTarget)return;setError("");if(!allowedTarget(editTarget.url))return setError("Target must be a valid HTTP(S) URL.");try{const expiry=editTarget.authorizationExpiresAt?new Date(editTarget.authorizationExpiresAt).toISOString():undefined;await updateTarget(editTarget.id,{url:editTarget.url,name:editTarget.name,environment:editTarget.environment,tags:editTarget.tags,authorized:editTarget.authorized,authorizationExpiresAt:expiry});setEditTarget(null);await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function removeTarget(){if(!editTarget)return;setError("");try{await deleteTarget(editTarget.id);setEditTarget(null);await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}

  async function startScan(t:Target,module=scanModule){setError("");if(!t.authorized)return setError("This target is not authorized.");if(t.authorizationExpiresAt&&new Date(t.authorizationExpiresAt)<new Date())return setError("Authorization for this target has expired.");if(running.includes(t.id!))return setError("Scan is already running for this target.");setRunning([...running,t.id!]);try{const result=await runScan(t.url,module);const scan:ScanRecord={targetId:t.id!,projectId:t.projectId,scanner:module,status:result.findings.length>0?"complete":"complete",findingsCount:result.findings.length,statusCode:result.status_code,finalUrl:result.url,createdAt:new Date().toISOString(),startedAt:new Date().toISOString(),finishedAt:new Date().toISOString()};const scanId=await addScan(scan);for(const f of result.findings){await addFinding({scanId:Number(scanId),targetId:t.id!,check:f.check,title:f.title,severity:f.severity,status:f.status,description:f.description,evidence:f.evidence,recommendation:f.recommendation,reference:f.reference,value:f.value,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})}await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setRunning(running.filter(id=>id!==t.id))}}
  
  async function updateFindingStatus(f:Finding,newStatus:string){setError("");try{await updateFinding(f.id!,{status:newStatus,updatedAt:new Date().toISOString()});setSelectedFinding(null);await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  
  async function generateReport(scan:Scan){const t=targets.find(x=>x.id===scan.targetId);if(!t)return setError("Target no longer exists.");const fs=findings.filter(x=>x.scanId===scan.id);const proj=projects.find(p=>p.id===scan.projectId);const html=buildAssessmentReport(t.url,{id:scan.id,status:scan.status,findingsCount:scan.findingsCount,statusCode:scan.statusCode,finalUrl:scan.finalUrl,createdAt:scan.createdAt,startedAt:scan.startedAt,finishedAt:scan.finishedAt},fs.map(f=>({id:f.id,scanId:f.scanId,check:f.check,title:f.title,severity:f.severity,status:f.status,description:f.description,evidence:f.evidence,recommendation:f.recommendation,reference:f.reference,value:f.value})),{name:proj?.name,client:proj?.client,description:proj?.description});await addReport({projectId:scan.projectId,scanId:scan.id,name:`${t.url} - ${fmt(scan.createdAt)}`,createdAt:new Date().toISOString()});await reload();openAssessmentReport(html)}
  
  async function deleteReportRecord(r:ReportRecord){setError("");try{await deleteReport(r.id!);await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}

  async function checkUpdates(){setCheckingUpdate(true);setUpdateText("Checking GitHub release channel…");try{const result=await checkForUpdate((p:UpdateProgress)=>{if(p.event==="Started")setUpdateText(`Downloading update…`);else if(p.event==="Progress")setUpdateText(`Downloading: ${Math.round(p.downloaded/1024)}KB`);else setUpdateText("Update complete. Restarting…")});if(result){setTimeout(async()=>{await restartAfterUpdate()},1500)}else setUpdateText("Application is up to date.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setCheckingUpdate(false);setTimeout(()=>setUpdateText(""),3000)}}

  const openFindings=findings.filter(f=>f.status!=="resolved"&&f.status!=="false positive"),critical=findings.filter(f=>f.severity.toLowerCase()==="critical").length,high=findings.filter(f=>f.severity.toLowerCase()==="high").length,medium=findings.filter(f=>f.severity.toLowerCase()==="medium").length,low=findings.filter(f=>f.severity.toLowerCase()==="low").length;
  const projectTargets=selectedProject?targets.filter(t=>t.projectId===Number(selectedProject)):[];
  const filteredFindings=findingFilter==="all"?findings:findings.filter(f=>f.severity.toLowerCase()===findingFilter);
  if(!loaded)return <div className="loading-screen"><div className="loading-mark">DD</div><b>Starting DadaDevourer</b><span>Loading local assessment database…</span></div>;

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark">DD</div><div><strong>DadaDevourer</strong><span>Security assessment</span></div></div>
      <div className="side-label">WORKSPACE</div><nav>{sections.map(s=><button key={s} className={active===s?"nav-item active":"nav-item"} onClick={()=>{setError("");setActive(s)}}><span className="nav-glyph">{["D","P","T","S","F","R","⚙"][sections.indexOf(s)]}</span><span>{s}</span></button>)}</nav>
      <div className="scope-card"><span className="status-dot"/><div><b>Local engine ready</b><small>Authorized testing only</small></div></div>
    </aside>
    <main className="content">
      <header className="topbar"><div><span className="eyebrow">DADADEVOURER • DESKTOP</span><h1>{active}</h1></div><div className="top-actions"><span className="engine-state"><span className="status-dot"/><span>v{version}</span></span><button className="secondary icon-button" onClick={checkUpdates} disabled={checkingUpdate}>↻ Update</button></div></header>
      {error&&<div className="error-banner"><b>Action needs attention</b><span>{error}</span><button onClick={()=>setError("")}>×</button></div>}
      {updateText&&<div className="info-banner">{updateText}</div>}

      {active==="Dashboard"&&<><section className="hero"><div><span className="eyebrow">AUTHORIZED SECURITY ASSESSMENT</span><h2>Assess your systems with a clear, repeatable workflow.</h2><p>Organize targets into projects. Confirm authorization. Run scans. Review findings. Generate reports.</p></div></section>
      <section className="stats"><div><span>Projects</span><b>{projects.length}</b><small>Assessment workspaces</small></div><div><span>Authorized targets</span><b>{targets.length}</b><small>Stored and ready</small></div><div><span>Completed scans</span><b>{scans.length}</b><small>Assessment runs</small></div><div><span>Open findings</span><b>{openFindings.length}</b><small>Awaiting review</small></div></section>
      <section className="grid-2"><div className="panel"><div className="panel-heading"><div><h3>Assessment workflow</h3><p>Keep every test tied to an authorized project.</p></div></div><div className="workflow-steps"><div className="step"><span>1</span> Create a project</div><div className="step"><span>2</span> Add authorized targets</div><div className="step"><span>3</span> Confirm scope and authorization</div><div className="step"><span>4</span> Run security assessments</div><div className="step"><span>5</span> Review and confirm findings</div><div className="step"><span>6</span> Generate and export reports</div></div></div>
      <div className="panel"><div className="panel-heading"><div><h3>Risk overview</h3><p>Current findings from all local scans.</p></div></div><div className="risk-list">{[["Critical",critical],["High",high],["Medium",medium],["Low",low]].map(([label,count])=><div key={label} className="risk-item"><span className={`severity-badge severity-${sevClass(label as string)}`}>{label}</span><b>{count}</b></div>)}</div></div></section></>}

      {active==="Projects"&&<section className="grid-2"><div className="panel"><div className="panel-heading"><div><h3>New assessment project</h3><p>Every target and scan belongs to a project.</p></div></div><div className="form-grid"><label><span>Project name</span><input placeholder="e.g., Acme Corp Q1 Assessment" value={projectName} onChange={e=>setProjectName(e.target.value)}/></label><label><span>Client name</span><input placeholder="e.g., Acme Corporation" value={client} onChange={e=>setClient(e.target.value)}/></label><label className="full"><span>Description</span><input placeholder="Notes about this assessment project…" value={projectDescription} onChange={e=>setProjectDescription(e.target.value)}/></label><button onClick={createProject} className="full">Create project</button></div></div>
      <div className="panel"><div className="panel-heading"><div><h3>Assessment projects</h3><p>{projects.length===0?"No projects created yet.":""}</p></div></div>{projects.length===0?<Empty title="No projects" text="Create a project to organize your assessment work." />:<div className="list">{projects.map(p=><div key={p.id} className="list-row"><div><b>{p.name}</b>{p.client&&<div className="sub">{p.client}</div>}{p.description&&<div className="sub">{p.description}</div>}<small>{fmt(p.createdAt)}</small></div><div className="list-actions"><button className="ghost-button" onClick={()=>setEditProject(p)}>Edit</button></div></div>)}</div>}</div></section>}

      {active==="Targets"&&<section className="grid-2"><div className="panel"><div className="panel-heading"><div><h3>Add authorized target</h3><p>A scope confirmation is required for every target.</p></div></div><div className="form-grid"><label><span>Project</span><select value={selectedProject} onChange={e=>setSelectedProject(e.target.value as any)}><option value="">Select a project…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="full"><span>Target URL (HTTP/HTTPS)</span><input type="url" placeholder="https://example.com" value={targetUrl} onChange={e=>setTargetUrl(e.target.value)}/></label><label><span>Name (optional)</span><input placeholder="e.g., Main web app" value={targetName} onChange={e=>setTargetName(e.target.value)}/></label><label><span>Environment</span><select value={targetEnv} onChange={e=>setTargetEnv(e.target.value)}><option>production</option><option>staging</option><option>development</option></select></label><label className="full"><span>Tags (optional)</span><input placeholder="e.g., web,critical" value={targetTags} onChange={e=>setTargetTags(e.target.value)}/></label><label className="full"><input type="checkbox" checked={scopeConfirmed} onChange={e=>setScopeConfirmed(e.target.checked)}/> <span>I own this system or have written authorization to test it</span></label><label className="full"><span>Authorization expires (optional)</span><input type="date" value={targetAuthExpiry} onChange={e=>setTargetAuthExpiry(e.target.value)}/></label><button onClick={createTarget} className="full">Add target</button></div></div>
      <div className="panel"><div className="panel-heading"><div><h3>Authorized targets</h3><p>{targets.length===0?"No targets added yet.":""}</p></div></div>{targets.length===0?<Empty title="No targets" text="Add an authorized target to begin assessment." />:<div className="list">{targets.map(t=>{const daysLeft=daysUntilExpiry(t.authorizationExpiresAt);return <div key={t.id} className="list-row target-card"><div><b>{t.name||t.url}</b><div className="sub">{t.url}</div>{t.environment&&<div className="sub">Environment: {t.environment}</div>}{t.tags&&<div className="sub">Tags: {t.tags}</div>}{!t.authorized?<span className="badge unauth">Not authorized</span>:daysLeft!==null&&daysLeft<7?<span className="badge warning">Expires in {daysLeft}d</span>:null}<small>{fmt(t.createdAt)}</small></div><div className="list-actions"><button className="ghost-button" onClick={()=>setEditTarget(t)}>Edit</button></div></div>})}</div>}</div></section>}

      {active==="Scans"&&<section className="panel"><div className="panel-heading"><div><h3>Assessment runs</h3><p>Run one controlled module or the complete local assessment.</p></div><div className="scan-launch"><select value={scanModule} onChange={e=>setScanModule(e.target.value as ScanModule)}>{modules.map(m=><option key={m[0]} value={m[0]}>{m[1]}</option>)}</select></div></div>{scans.length===0?<Empty title="No scans run yet" text="Select a target above to begin assessment." />:<div className="scan-table">{scans.map(s=>{const t=targets.find(x=>x.id===s.targetId);return <div key={s.id} className="scan-card"><div><b>#{s.id} – {t?.name||t?.url}</b><div className="sub">{s.scanner} scan</div><div className="sub">Findings: {s.findingsCount}</div><div className="sub">{fmt(s.finishedAt||s.createdAt)}</div></div><div className="list-actions"><button className="ghost-button" onClick={()=>setReportScanId(s.id)}>Report</button></div></div>})}</div>}</section>}

      {active==="Findings"&&<section className="panel"><div className="panel-heading"><div><h3>Findings & evidence</h3><p>Review, classify and track observations from completed scans.</p></div><div><select value={findingFilter} onChange={e=>setFindingFilter(e.target.value)}><option value="all">All findings ({findings.length})</option><option value="critical">Critical ({findings.filter(f=>f.severity.toLowerCase()==="critical").length})</option><option value="high">High ({findings.filter(f=>f.severity.toLowerCase()==="high").length})</option><option value="medium">Medium ({findings.filter(f=>f.severity.toLowerCase()==="medium").length})</option><option value="low">Low ({findings.filter(f=>f.severity.toLowerCase()==="low").length})</option></select></div></div>{filteredFindings.length===0?<Empty title="No findings" text="Run a scan to discover observations." />:<div className="list">{filteredFindings.map(f=><div key={f.id} className="list-row finding-card"><div><span className={`severity-badge severity-${sevClass(f.severity)}`}>{f.severity}</span><b>{f.title||f.check}</b><div className="sub">{f.check}</div><small className={`status-${sevClass(f.status)}`}>{f.status}</small></div><div className="list-actions"><button className="ghost-button" onClick={()=>setSelectedFinding(f)}>Review</button></div></div>)}</div>}</section>}

      {active==="Reports"&&<section className="grid-2"><div className="panel"><div className="panel-heading"><div><h3>Generate assessment report</h3><p>Build a local report from a completed scan.</p></div></div>{scans.length===0?<p className="muted">No scans available. Run an assessment to generate reports.</p>:<div className="form-grid"><label><span>Select scan</span><select value={reportScanId} onChange={e=>setReportScanId(e.target.value as any)}><option value="">Choose a scan…</option>{scans.map(s=>{const t=targets.find(x=>x.id===s.targetId);return <option key={s.id} value={s.id}>#{s.id} – {t?.url} ({fmt(s.createdAt)})</option>})}</select></label>{reportScanId&&<button onClick={()=>{generateReport(scans.find(s=>s.id===reportScanId)!)}} className="full">Generate & open report</button>}</div>}</div>
      <div className="panel"><div className="panel-heading"><div><h3>Report history</h3><p>{reports.length===0?"No reports generated yet.":""}</p></div></div>{reports.length===0?<Empty title="No reports" text="Generate a report from a completed scan to save it here." />:<div className="list">{reports.map(r=><div key={r.id} className="list-row"><div><b>{r.name}</b><small>{fmt(r.createdAt)}</small></div><div className="list-actions"><button className="ghost-button" onClick={()=>deleteReportRecord(r)}>Delete</button></div></div>)}</div>}</div></section>}

      {active==="Settings"&&<section className="grid-2"><div className="panel"><div className="panel-heading"><div><h3>Application</h3><p>Local-first security assessment workstation.</p></div></div><div className="settings-actions"><div><b>Version</b><p className="muted">{version}</p></div><div><b>Database</b><p className="muted">SQLite local persistence in application data directory</p></div><div><b>Scanner</b><p className="muted">Bundled Python sidecar with timeout protection</p></div><div><b>Authorization</b><p className="muted">All assessments require target authorization confirmation</p></div></div></div>
      <div className="panel"><div className="panel-heading"><div><h3>Data export</h3><p>Export all assessment data as JSON for backup.</p></div></div><button onClick={async()=>{const {exportAssessmentData}=await import("./backup");await exportAssessmentData({projects,targets,scans,findings,reports,audit})}} className="full">Export assessment data</button></div></section>}

      {editProject&&<div className="modal-overlay" onClick={()=>setEditProject(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>Edit project</h2><button className="close-btn" onClick={()=>setEditProject(null)}>×</button></div><div className="modal-body"><div className="form-grid"><label><span>Project name</span><input value={editProject.name} onChange={e=>setEditProject({...editProject,name:e.target.value})}/></label><label><span>Client</span><input value={editProject.client} onChange={e=>setEditProject({...editProject,client:e.target.value})}/></label><label className="full"><span>Description</span><input value={editProject.description||""} onChange={e=>setEditProject({...editProject,description:e.target.value})}/></label><label><span>Status</span><select value={editProject.status} onChange={e=>setEditProject({...editProject,status:e.target.value})}><option>active</option><option>archived</option></select></label></div></div><div className="modal-footer"><button onClick={saveProjectEdit}>Save changes</button><button className="secondary" onClick={()=>{if(confirm("Delete this project? This cannot be undone.")){removeProject()}}}>Delete</button><button className="ghost-button" onClick={()=>setEditProject(null)}>Cancel</button></div></div></div>}

      {editTarget&&<div className="modal-overlay" onClick={()=>setEditTarget(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>Edit target</h2><button className="close-btn" onClick={()=>setEditTarget(null)}>×</button></div><div className="modal-body"><div className="form-grid"><label className="full"><span>Target URL</span><input type="url" value={editTarget.url} onChange={e=>setEditTarget({...editTarget,url:e.target.value})}/></label><label><span>Name</span><input value={editTarget.name||""} onChange={e=>setEditTarget({...editTarget,name:e.target.value})}/></label><label><span>Environment</span><select value={editTarget.environment||"production"} onChange={e=>setEditTarget({...editTarget,environment:e.target.value})}><option>production</option><option>staging</option><option>development</option></select></label><label className="full"><span>Tags</span><input value={editTarget.tags||""} onChange={e=>setEditTarget({...editTarget,tags:e.target.value})}/></label><label className="full"><input type="checkbox" checked={editTarget.authorized} onChange={e=>setEditTarget({...editTarget,authorized:e.target.checked})}/> <span>Authorized for testing</span></label><label className="full"><span>Authorization expires</span><input type="date" value={editTarget.authorizationExpiresAt?editTarget.authorizationExpiresAt.split("T")[0]:""} onChange={e=>setEditTarget({...editTarget,authorizationExpiresAt:e.target.value?new Date(e.target.value).toISOString():undefined})}/></label></div></div><div className="modal-footer"><button onClick={saveTargetEdit}>Save changes</button><button className="secondary" onClick={()=>{if(confirm("Delete this target?")){removeTarget()}}}>Delete</button><button className="ghost-button" onClick={()=>setEditTarget(null)}>Cancel</button></div></div></div>}

      {selectedFinding&&<div className="modal-overlay" onClick={()=>setSelectedFinding(null)}><div className="modal modal-lg" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>{selectedFinding.title||selectedFinding.check}</h2><button className="close-btn" onClick={()=>setSelectedFinding(null)}>×</button></div><div className="modal-body"><div><span className={`severity-badge severity-${sevClass(selectedFinding.severity)}`}>{selectedFinding.severity}</span><span className={`status-badge status-${sevClass(selectedFinding.status)}`}>{selectedFinding.status}</span></div>{selectedFinding.description&&<div><h4>Description</h4><p>{selectedFinding.description}</p></div>}{selectedFinding.evidence&&<div><h4>Evidence</h4><pre className="evidence-block">{selectedFinding.evidence}</pre></div>}{selectedFinding.recommendation&&<div><h4>Recommendation</h4><p>{selectedFinding.recommendation}</p></div>}{selectedFinding.reference&&<div><h4>Reference</h4><p>{selectedFinding.reference}</p></div>}</div><div className="modal-footer"><label><span>Status</span><select value={selectedFinding.status} onChange={e=>updateFindingStatus(selectedFinding,e.target.value)}><option>open</option><option>confirmed</option><option>false positive</option><option>accepted</option><option>resolved</option></select></label><button className="ghost-button" onClick={()=>setSelectedFinding(null)}>Close</button></div></div></div>}

      {reportScanId&&<div className="modal-overlay" onClick={()=>setReportScanId("")}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>Generate Report</h2><button className="close-btn" onClick={()=>setReportScanId("")}>×</button></div><div className="modal-body"><p>The report will be generated and opened in your browser. You can print or save it as PDF.</p></div><div className="modal-footer"><button onClick={()=>{generateReport(scans.find(s=>s.id===reportScanId)!)}}>Generate & open</button><button className="ghost-button" onClick={()=>setReportScanId("")}>Cancel</button></div></div></div>}
    </main>
  </div>
}

function Empty({title,text}:{title:string;text:string}){return <div className="empty-state"><div className="empty-icon">—</div><h2>{title}</h2><p>{text}</p></div>}
